### ISSUE TITLE
К исправлению

### ISSUE THREAD

**Issue by Cvtx** [Cvtx/CRC-Asm#1]
Добавить очистку текстового поля сообщения после завершения вычислений.
Обработать исключения нажатия кнопки 'завершить вычисление' при начальных данных.
Снять ограничение на длину сообщения.
Не хватает справки, интуитивного интерфейса.
Убрать удаление по кнопки продолжения, добавить отдельную кнопку.
Скрыть неактивные элементы интерфейса при запуске программы.
Добавить дополнительные возможности контроля вычисления (по байтам).

**Comment by DnineO** [comment]
Написать отчет.

**Comment by Cvtx** [comment]
Все исправления и доработки внесены
